apiVersion: apps/v1
kind: Deployment
metadata:
  name: nkd-caais-middleware-deployment
  namespace: nkd
  labels:
    app.kubernetes.io/name: caais-middleware
spec:
  template:
    spec:
      containers:
        - name: nkd-caais-middleware
          image: ghcr.io/datagov-cz/caais-middleware@sha256:4687df9b0e13b1458bfc4198dc99b72f16b434126e46df4f5919b9b02363d97e
          resources:
            requests:
              memory: "128Mi"
            limits:
              memory: "256Mi"
