apiVersion: apps/v1
kind: Deployment
metadata:
  name: nkd-design-system-deployment
  namespace: nkd
  labels:
    app.kubernetes.io/name: design-system
spec:
  template:
    spec:
      containers:
        - name: nkd-design-system
          resources:
            requests:
              memory: "16Mi"
            limits:
              memory: "32Mi"
