apiVersion: apps/v1
kind: Deployment
metadata:
  name: nkd-ldf-deployment
  namespace: nkd
  labels:
    app.kubernetes.io/name: ldf
spec:
  template:
    spec:
      containers:
        - name: nkd-ldf
          resources:
            requests:
              memory: "256Mi"
            limits:
              memory: "512Mi"
