apiVersion: apps/v1
kind: Deployment
metadata:
  name: nkd-linkedpipes-etl-deployment
  namespace: nkd
  labels:
    app.kubernetes.io/name: linkedpipes-etl
spec:
  template:
    spec:
      containers:
        - name: nkd-linkedpipes-etl-executor
          image: ghcr.io/linkedpipes/etl-executor:develop
          command: ["java", "-DconfigFileLocation=/opt/lp-etl/configuration/configuration.properties", "-Xmx4g", "-jar" ,"./executor/executor.jar"]
          resources:
            requests:
              memory: "4Gi"
            limits:
              memory: "5Gi"
        - name: nkd-linkedpipes-etl-executor-monitor
          image: ghcr.io/linkedpipes/etl-executor-monitor:develop
          env:
            - name: LP_ETL_EXECUTION_HISTORY_COUNT_LIMIT
              value: ""
          resources:
            requests:
              memory: "128Mi"
            limits:
              memory: "512Mi"
        - name: nkd-linkedpipes-etl-frontend
          image: ghcr.io/linkedpipes/etl-frontend:develop
          resources:
            requests:
              memory: "128Mi"
            limits:
              memory: "256Mi"
        - name: nkd-linkedpipes-etl-storage
          image: ghcr.io/linkedpipes/etl-storage:develop
          resources:
            requests:
              memory: "128Mi"
            limits:
              memory: "512Mi"
        - name: nkd-orchestrator
          image: ghcr.io/datagov-cz/nkd-orchestrator:develop
          resources:
            requests:
              memory: "32Mi"
            limits:
              memory: "64Mi"
