name: nkod-database
services:
  solr:
    image: ghcr.io/datagov-cz/nkod-solr:${DEPLOYMENT_ENVIRONMENT}
    build:
      context: ../solr
    ports:
      - 8983:8983
    restart: always
    volumes:
      - solr-data:/var/solr
  couchdb:
    image: ghcr.io/datagov-cz/nkod-couchdb:${DEPLOYMENT_ENVIRONMENT}
    build:
      context: ../couchdb
    environment:
      COUCHDB_USER: ${COUCHDB_USER}
      COUCHDB_PASSWORD: ${COUCHDB_PASSWORD}
    ports:
      - 5984:5984
    restart: always
    volumes:
      - couchdb-data:/opt/couchdb/data
volumes:
  solr-data:
    name: nkod-solr-data
    external: True
  couchdb-data:
    name: nkod-couchdb-data
    external: True
