apiVersion: apps/v1
kind: Deployment
metadata:
  name: nkd-adapter-deployment
  namespace: nkd
  labels:
    app.kubernetes.io/name: adapter
spec:
  template:
    spec:
      containers:
        # We do not deploy nkd-registration-manager to production.
        - name: nkd-registration-manager
          $patch: delete
