apiVersion: apps/v1
kind: Deployment
metadata:
  name: nkd-solr-deployment
  namespace: nkd
  labels:
    app.kubernetes.io/name: solr
spec:
  template:
    spec:
      tolerations:
        - key: dedicated
          operator: Equal
          value: user1
          effect: NoSchedule
      nodeSelector:
        agentpool: user1
      containers:
        - name: nkd-solr
          resources:
            requests:
              memory: "1Gi"
            limits:
              memory: "2Gi"
