apiVersion: apps/v1
kind: Deployment
metadata:
  name: nkd-virtuoso-ndc-deployment
  namespace: nkd
  labels:
    app.kubernetes.io/name: virtuoso-ndc
spec:
  template:
    spec:
      containers:
        - name: nkd-virtuoso
          env:
            - name: VIRT_PARAMETERS_NUMBEROFBUFFERS
              value: "850000"
            - name: VIRT_PARAMETERS_MAXDIRTYBUFFERS
              value: "650000"
          resources:
            requests:
              memory: "10Gi"
            limits:
              memory: "11Gi"
        - name: ssh-server
          resources:
            requests:
              memory: "256Mi"
            limits:
              memory: "512Mi"
