apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nkod-adapter-pvc
  namespace: nkod
  labels:
    app.kubernetes.io/name: adapter
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 32Gi
