apiVersion: apps/v1
kind: Deployment
metadata:
  name: nkod-catalog-deployment
  namespace: nkod
  labels:
    app.kubernetes.io/name: catalog
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: catalog
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: catalog
    spec:
      containers:
        - name: nkod-catalog
          image: ghcr.io/datagov-cz/nkod-catalog:develop
          imagePullPolicy: Always
          env:
            - name: NODE_ENV
              value: "production"
            - name: HOST
              value: "0.0.0.0"
            - name: PORT
              value: "80"
            - name: SOLR_URL
              value: "http://nkod-solr:8983/solr/"
            - name: COUCHDB_URL
              value: "http://nkod-couchdb:5984"
            - name: HTTP_SERVE_STATIC
              value: "1"
            - name: DESIGN_SYSTEM_FOLDER
              value: ""
            - name: LABEL_CACHE_RELOAD_CRON
              value: "0/15 * * * *"
            - name: QUALITY_SPARQL_URL
              value: "http://nkod-virtuoso:8890/sparql"
            - name: CLIENT_CATALOG_FORM_URL
              value: "http://http://172.205.23.154/formulář/"
            - name: CLIENT_APPLICATION_FORM_URL
              value: "http://http://172.205.23.154/aplikace-registrace"
            - name: CLIENT_SUGGESTION_FORM_URL
              value: "http://http://172.205.23.154/návrhy-registrace"
            - name: CLIENT_DEREFERENCE
              value: ""
            - name: CLIENT_DASHBOARD_PUBLISHER_DAILY
              value: "/kibana/"
            - name: CLIENT_DASHBOARD_PUBLISHER_MONTHLY
              value: "/kibana/"
            - name: CLIENT_SPARQL_EDITOR_URL
              value: "https://yasgui.triply.cc/"
            - name: CLIENT_SPARQL_DEFAULT_QUERY
              value: >
                SELECT ?typ (COUNT(?s) AS ?pocet)
                WHERE {
                  ?s a ?typ
                }
                GROUP BY ?typ
                ORDER BY DESC(COUNT(?s))
                LIMIT 10
            - name: CLIENT_DATA_SERVICE_CLASS_AND_PROPERTIES_TEMPLATE
              value: ""
            - name: CLIENT_MATOMO_URL
              value: ""
            - name: CLIENT_MATOMO_SITE_ID
              value: ""
            - name: CLIENT_CATALOG_VALIDATOR_LANDING_PAGE
              value: "https://datagov-cz.github.io/lkod-validator/"
            - name: CLIENT_CATALOG_VALIDATOR_RUN_VALIDATION
              value: "https://datagov-cz.github.io/lkod-validator?catalog={}"
            - name: DESIGN_SYSTEM_URL
              value: "http://172.205.23.154/assets/design-system/"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nkod-catalog
  namespace: nkod
  labels:
    app.kubernetes.io/name: catalog
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: catalog
  ports:
  - protocol: TCP
    targetPort: 80
    port: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nkod-catalog-ingress
  namespace: nkod
  labels:
    app.kubernetes.io/name: virtuoso
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      # datové-sady, datová-sada, datasets, dataset
      # aplikace, detail-aplikace, applications, application
      # poskytovatelé, publishers
      # lokální-katalogy, local-catalogs
      # návrhy-na-datové-sady-k-otevření, návrh-na-datovou-sadu-k-otevření, suggestions-for-datasets-to-be-opened, suggestion-for-dataset-to-be-opened
      - path: /assets/catalog
        pathType: Prefix
        backend:
          service:
            name: nkod-catalog
            port:
              number: 80
      - path: /datasets
        pathType: Prefix
        backend:
          service:
            name: nkod-catalog
            port:
              number: 80
      - path: /dataset
        pathType: Prefix
        backend:
          service:
            name: nkod-catalog
            port:
              number: 80
