apiVersion: apps/v1
kind: Deployment
metadata:
  name: nkd-catalog-deployment
  namespace: nkd
  labels:
    app.kubernetes.io/name: catalog
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: catalog
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: catalog
    spec:
      containers:
        - name: nkd-catalog
          image: ghcr.io/datagov-cz/nkd-catalog:develop
          imagePullPolicy: Always
          env:
            - name: NODE_ENV
              value: "production"
            - name: HOST
              value: "0.0.0.0"
            - name: PORT
              value: "80"
            - name: SOLR_URL
              value: "http://nkd-solr:8983/solr/"
            - name: COUCHDB_URL
              value: "http://nkd-couchdb:5984"
            - name: HTTP_SERVE_STATIC
              value: "1"
            - name: DESIGN_SYSTEM_FOLDER
              value: ""
            - name: LABEL_CACHE_RELOAD_CRON
              value: "0/15 * * * *"
            - name: QUALITY_SPARQL_URL
              value: "http://nkd-virtuoso:8890/sparql"
            - name: DATA_PORTAL_DOMAIN_NAME
              valueFrom:
                configMapKeyRef:
                  name: nkd-configuration
                  key: data_portal_domain_name
            - name: CLIENT_CATALOG_FORM_URL
              value: "https://$(DATA_PORTAL_DOMAIN_NAME)/formulář/"
            - name: CLIENT_APPLICATION_FORM_URL
              value: "https://forms.office.com/e/mK4wLvrww4"
            - name: CLIENT_SUGGESTION_FORM_URL
              value: "https://forms.office.com/e/UuwD7UBnRG"
            - name: CLIENT_DEREFERENCE
              value: ""
            - name: CLIENT_DASHBOARD_PUBLISHER_DAILY
              value: "/kibana/"
            - name: CLIENT_DASHBOARD_PUBLISHER_MONTHLY
              value: "/kibana/"
            - name: CLIENT_SPARQL_EDITOR_URL
              value: "https://yasgui.triply.cc/"
            - name: CLIENT_SPARQL_DEFAULT_QUERY
              value: >
                SELECT ?typ (COUNT(?s) AS ?pocet)
                WHERE {
                  ?s a ?typ
                }
                GROUP BY ?typ
                ORDER BY DESC(COUNT(?s))
                LIMIT 10
            - name: CLIENT_DATA_SERVICE_CLASS_AND_PROPERTIES_TEMPLATE
              value: ""
            - name: CLIENT_MATOMO_URL
              value: ""
            - name: CLIENT_MATOMO_SITE_ID
              value: ""
            - name: CLIENT_CATALOG_VALIDATOR_LANDING_PAGE
              value: "https://datagov-cz.github.io/lkod-validator/"
            - name: CLIENT_CATALOG_VALIDATOR_RUN_VALIDATION
              value: "https://datagov-cz.github.io/lkod-validator?catalog={}"
            - name: DESIGN_SYSTEM_URL
              value: "/assets/design-system/"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nkd-catalog
  namespace: nkd
  labels:
    app.kubernetes.io/name: catalog
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: catalog
  ports:
  - protocol: TCP
    targetPort: 80
    port: 80
