apiVersion: v1
kind: Secret
metadata:
  name: nkd-adapter-secret
  namespace: nkd
  labels:
    app.kubernetes.io/name: adapter
type: Opaque
data:
---
apiVersion: v1
kind: Secret
metadata:
  name: nkd-couchdb-secret
  namespace: nkd
  labels:
    app.kubernetes.io/name: couchdb
type: Opaque
data:
---
apiVersion: v1
kind: Secret
metadata:
  name: nkd-graphql-secret
  namespace: nkd
  labels:
    app.kubernetes.io/name: graphql
type: Opaque
data:
---
apiVersion: v1
kind: Secret
metadata:
  name: nkd-ldf-secret
  namespace: nkd
  labels:
    app.kubernetes.io/name: graphql
type: Opaque
data:
---
apiVersion: v1
kind: Secret
metadata:
  name: nkd-virtuoso-ndc-secret
  namespace: nkd
  labels:
    app.kubernetes.io/name: virtuoso-ndc
data:
---
apiVersion: v1
kind: Secret
metadata:
  name: nkd-virtuoso-vocabulary-secret
  namespace: nkd
  labels:
    app.kubernetes.io/name: virtuoso-vocabulary
type: Opaque
data:
---
apiVersion: v1
kind: Secret
metadata:
  name: nkd-portal
  namespace: nkd
  labels:
    app.kubernetes.io/name: portal-data-gov-cz
type: Opaque
data:
---
apiVersion: v1
kind: Secret
metadata:
  name: nkd-caais-middleware-secret
  namespace: nkd
  labels:
    app.kubernetes.io/name: caais-middleware
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: nkd-registration-manager-secret
  namespace: nkd
  labels:
    app.kubernetes.io/name: registration-manager
type: Opaque
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nkd-configuration
  namespace: nkd
data:
