apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nkod-public-pvc
  namespace: nkod
  labels:
    app.kubernetes.io/name: public
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 128Gi
